### ISSUE TITLE
Can not compile in ubuntu 24.10

### ISSUE THREAD

**Issue by Pianisimo** [jeremychone/rust-simple-fs#2]
```
error[E0308]: mismatched types
  --> /home/sergio/.cargo/registry/src/index.crates.io-6f17d22bba15001f/simple-fs-0.2.2/src/watch.rs:84:26
   |
84 |         notify_full_debouncer: debouncer,
   |                                ^^^^^^^^^ expected `Debouncer<INotifyWatcher, FileIdMap>`, found `Debouncer<INotifyWatcher, NoCache>`
   |
   = note: expected struct `Debouncer<_, FileIdMap>`
              found struct `Debouncer<_, NoCache>`

For more information about this error, try `rustc --explain E0308`.
error: could not compile `simple-fs` (lib) due to 1 previous error
```

**Comment by jeremychone** [comment]
Thanks for reporting.

I updated the Notifier crate, so this could be the issue. I will try to reproduce it on Ubuntu when I have a chance.

In the meantime, if you have any ideas, feel free to share. I can roll back to the previous notify crate if really needed.

**Comment by Pianisimo** [comment]
Thanks for replying, unfortunately no luck finding a quick fix or workaround, feel free to ask anything, will do my best to help.

**Comment by jeremychone** [comment]
Ho, I think I found it. I needed to use the type alias `RecommendedCache`. 
let me do some test, and another release.

**Comment by jeremychone** [comment]
Ok, I pushed version `v0.2.4` with the fixed. Hope it works!

**Comment by jeremychone** [comment]
Fixed in `v0.2.4`

**Comment by Pianisimo** [comment]
Thanks a lot. 
Bests of lucks.
